stages:
  - test
  - build_static_assets
  - build_docker_image
  - deploy

.js:
  image: node
  before_script:
    - node --version
    - npm --version
    - yarn --version
    - yarn

test:
  extends: .js
  stage: test
  script:
    - yarn test

build_static_assets:
  extends: .js
  stage: build_static_assets
  script:
    - yarn build:local
  artifacts:
    paths:
      - build/

build_docker_image:
  stage: build_docker_image
  image: docker
  services:
    - docker:dind
  script:
    - env
    - echo ${CONTAINER_IMAGE}
    - echo ${CI_REGISTRY_IMAGE}
    - echo ${CI_COMMIT_SHORT_SHA}
    - echo ${CI_COMMIT_REF_SLUG}
    - echo ${EMBASSY_KUBECONFIG}
    - echo ${KUBECONFIG}
    - ls
    - docker build -t disease-portal-client-nginx-image .
    - docker image ls
