stages:
  - test
  - build_static_assets
  - build_docker_image
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:latest

.js:
  image: node
  before_script:
    - node --version
    - npm --version
    - yarn --version
    - yarn

test:
  extends: .js
  stage: test
  script:
    - yarn test

build_static_assets:
  extends: .js
  stage: build_static_assets
  script:
    - yarn build:local
  artifacts:
    paths:
      - build/

build_docker_image:
  stage: build_docker_image
  image: docker:latest
  tags:
    - dind
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker --version
  script:
    - env
    - echo ${CONTAINER_IMAGE}
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"

deploy:
  stage: deploy
  image: alpine
  script:
    - kubectl apply -f k8s_deploy.yml
