stages:
  - test
  - build

image: node

default:
  before_script:
    - echo $PWD
    - ls
    - ls node_modules
    - which yarn
    - yarn --version
    - yarn

test:
  script:
    - yarn test

build:
  script:
    - yarn build
