stages:
  - test
  - build
  - deploy

.js:
  image: node
  before_script:
    - node --version
    - npm --version
    - yarn --version
    - yarn

test:
  extends: .js
  stage: test
  script:
    - yarn test

build:
  extends: .js
  stage: build
  script:
    - yarn build
  artifacts:
    name: disease-portal-client-artifact
    paths:
      - build/
# deploy:
#   stage: deploy
#   image: nginx
