stages:
  - test
  - build

image: node

default:
  before_script:
    - echo $PWD
    - which yarn
    - yarn --version
    - yarn
    - ls
    - ls node_modules

test:
  stage: test
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
