stages:
  - test
  - build_static_assets
  - build_docker_image
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:latest

.js:
  image: node
  before_script:
    - node --version
    - npm --version
    - yarn --version
    - yarn

test:
  extends: .js
  stage: test
  script:
    - yarn test

build_static_assets:
  extends: .js
  stage: build_static_assets
  script:
    - yarn build:local
  artifacts:
    paths:
      - build/

build_docker_image:
  stage: build_docker_image
  image: docker:latest
  tags:
    - dind
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker --version
    - echo ${CONTAINER_IMAGE}
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"

deploy:
  stage: deploy
  image: alpine
  environment:
    name: test
    kubernetes:
      namespace: dlrice
  before_script:
    - env
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - git clone https://gitlab.ebi.ac.uk/dlrice/k8s-config
    - mkdir -p ~/.kube
    - cp k8s-config/config ~/.kube/
    - cat ~/.kube/config
    - kubectl config view
    - kubectl config get-contexts
    - kubectl config use-context uniprot-admin-hx-wp-webadmin-02
    - kubectl config view
    - 'printf "$(kubectl create secret docker-registry gitlab-registry --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD --docker-email=$GITLAB_USER_EMAIL -o yaml --dry-run)" | kubectl apply -f -'
    - kubectl get secrets gitlab-registry -o yaml
    - kubectl get ns
    - kubectl config set-context --current --namespace=dlrice
    - kubectl config view
    - "kubectl config view --minify | grep namespace:"
