stages:
  - test
  - build

image: node

default:
  before_script:
    - node --version
    - npm --version
    - yarn --version
    - yarn

test:
  stage: test
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
  artifacts:
    name: disease-portal-client-artifact
    paths:
    - build/
