language: node_js
node_js:
  # lock to 11.10.1 due to https://github.com/facebook/jest/issues/8069
  - "11.10.1"
before_deploy:
  - npm run build
notifications:
  email:
    - xwatkins@ebi.ac.uk
  slack: ebi-uniprot:7OMFmmkUp9uxH3SXgyq7OVb3
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
