# config files for kubectl for Web-Prod Cloud
# variables for different data center(HX and HH) need to be set in GitLab
# no need for Embassy Cloud because we have permission to fully integrate it with GitLab
# See how to create a service account in gitlab-admin-service-account.yaml file
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: __K8S_CERTIFICATE__
      server: __K8S_URL__
    name: wp-webadmin-02
contexts:
  - context:
      cluster: wp-webadmin-02
      user: team-admin-wp-webadmin-02
      namespace: disease-service
    name: team-admin-wp-webadmin-02
current-context: team-admin-wp-webadmin-02
kind: Config
preferences: {}
users:
  - name: team-admin-wp-webadmin-02
    user:
      token: __K8S_USER_TOKEN__
